package com.example.productSecurity.pojo;

import lombok.*;

import java.math.BigDecimal;
import java.sql.Date;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.place
     *
     * @mbggenerated
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.distributor
     *
     * @mbggenerated
     */
    private String distributor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.QRcode
     *
     * @mbggenerated
     */
    private String QRcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.owner
     *
     * @mbggenerated
     */
    private Long owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.owner
     *
     * @mbggenerated
     */
    private String picture;


    public Product(String name, BigDecimal price, Date date, String place, String distributor, String QRcode, Long owner, String picture) {
        this.name = name;
        this.date = date;
        this.place = place;
        this.distributor = distributor;
        this.price = price;
        this.QRcode = QRcode;
        this.owner = owner;
        this.picture = picture;
    }

    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", price=" + price +
                ", date=" + date +
                ", place='" + place + '\'' +
                ", distributor='" + distributor + '\'' +
                ", QRcode='" + QRcode + '\'' +
                ", owner=" + owner +
                '}';
    }
}
